-- LoadData.sql (to run after CreateSchema.sql)

-- Use consistent relative paths from container working directory
LOAD DATA LOCAL INFILE './datasource/ItemTypes.csv' INTO TABLE `T_ItemType` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/UnitCategories.csv' INTO TABLE `T_UnitCategory` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Units.csv' INTO TABLE `T_Units` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Brokers.csv' INTO TABLE `T_Brokers` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Shippers.csv' INTO TABLE `T_Shippers` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Suppliers.csv' INTO TABLE `T_Suppliers` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/GrowingSeasons.csv' INTO TABLE `T_GrowingSeason` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/OrderItemTypes.csv' INTO TABLE `T_OrderItemTypes` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/OrderNotes.csv' INTO TABLE `T_OrderNotes` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Items.csv' INTO TABLE `T_Items` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Prices.csv' INTO TABLE `T_Prices` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Plantings.csv' INTO TABLE `T_Plantings` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Inventory.csv' INTO TABLE `T_Inventory` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Pitch.csv' INTO TABLE `T_Pitch` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Orders.csv' INTO TABLE `T_Orders` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/OrderItems.csv' INTO TABLE `T_OrderItems` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE './datasource/Sun.csv' INTO TABLE `T_Sun` 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;